id: fbd2f825-c3d5-4378-bf45-e1d77d69ae0f
pipeline_type: WORKSPACE
name: gold_pipeline
libraries:
  - glob:
      include: /Workspace/Users/rafiulislam7351@outlook.com/Spotify_Azure_Data_Engineering_Project/spotify_dab/src/gold/DLT/gold_pipeline/transformations/**
schema: gold
continuous: false
development: false
photon: true
channel: CURRENT
catalog: spotify_project
serverless: true
root_path: /Workspace/Users/rafiulislam7351@outlook.com/Spotify_Azure_Data_Engineering_Project/spotify_dab/src/gold/DLT/gold_pipeline
